var tableDiff = require('./table-diff.hbs');
var popupCompanyTal = require('../popupCompany/index.hbs');
var popupRecordTal = require('../popupCompany/record.hbs');
var Fn =  require('../function');
var data = {
    tLeftHead:['医院药品ID','药品名称','规格厂家','转换比','门诊/住院单位','是否停用','修订时间'],
    tRightHead:['药品编码','药品类型','药品名称','剂型','规格','转换比','企业简称','批准文号/注册证号','基药','重点药物监控','营养用药','中成药注射剂','精麻毒放','妊娠用药','抗菌药物','DDD值','给药途径(不计算强度)','是否计算强度','分级','人社分类','药理分类','是否PPI'],
    ydata:[{
        id:1,
        yid:'0000007119',
        yypmc:'氯米芬片◆①',
        yggcj:'50mg*10/盒  塞浦路斯麦',
        yzhb:'10',
        ymzzy:'片，盒，和',
        yty:'否',
        yxdrq:'2016.12.12'
    },{
        id:2,
        yid:'abc1',
        yypmc:'abc1',
        yggcj:'abc1',
        yzhb:'abc1',
        ymzzy:'abc1',
        yty:'abc1',
        yxdrq:'abc1'
    },{
        id:3,
        yid:'abc1',
        yypmc:'abc1',
        yggcj:'abc1',
        yzhb:'abc1',
        ymzzy:'abc1',
        yty:'abc1',
        yxdrq:'abc1'
    },{
        id:4,
        yid:'abc1',
        yypmc:'abc1',
        yggcj:'abc1',
        yzhb:'abc1',
        ymzzy:'abc1',
        yty:'abc1',
        yxdrq:'abc1'
    },{
        id:5,
        yid:'abc1',
        yypmc:'abc1',
        yggcj:'abc1',
        yzhb:'abc1',
        ymzzy:'abc1',
        yty:'abc1',
        yxdrq:'abc1'
    },{
        id:6,
        yid:'abc1',
        yypmc:'abc1',
        yggcj:'abc1',
        yzhb:'abc1',
        ymzzy:'abc1',
        yty:'abc1',
        yxdrq:'abc1'
    },{
        id:7,
        yid:'abc1',
        yypmc:'abc1',
        yggcj:'abc1',
        yzhb:'abc1',
        ymzzy:'abc1',
        yty:'abc1',
        yxdrq:'abc1'
    },{
        id:8,
        yid:'abc1',
        yypmc:'abc1',
        yggcj:'abc1',
        yzhb:'abc1',
        ymzzy:'abc1',
        yty:'abc1',
        yxdrq:'abc1'
    }],
    bdata:[{
        bbm:'X153818-10',
        blx:'化学药',
        bypmc:'枸橼酸氯米',
        bjx:'素片',
        bgg:'50mg',
        bzhb:'10',
        bqyjc:'麦道甘美',
        bpzwh:'国药准字',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    },{
        bbm:'abc',
        blx:'abc',
        bypmc:'abc',
        bjx:'abc',
        bgg:'abc',
        bzhb:'abc',
        bqyjc:'abc',
        bpzwh:'abc',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    },{
        bbm:'abc',
        blx:'abc',
        bypmc:'abc',
        bjx:'abc',
        bgg:'abc',
        bzhb:'abc',
        bqyjc:'abc',
        bpzwh:'abc',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    },{
        bbm:'abc',
        blx:'abc',
        bypmc:'abc',
        bjx:'abc',
        bgg:'abc',
        bzhb:'abc',
        bqyjc:'abc',
        bpzwh:'abc',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    },{
        bbm:'abc',
        blx:'abc',
        bypmc:'abc',
        bjx:'abc',
        bgg:'abc',
        bzhb:'abc',
        bqyjc:'abc',
        bpzwh:'abc',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    },{
        bbm:'abc',
        blx:'abc',
        bypmc:'abc',
        bjx:'abc',
        bgg:'abc',
        bzhb:'abc',
        bqyjc:'abc',
        bpzwh:'abc',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    },{
        bbm:'abc',
        blx:'abc',
        bypmc:'abc',
        bjx:'abc',
        bgg:'abc',
        bzhb:'abc',
        bqyjc:'abc',
        bpzwh:'abc',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    },{
        bbm:'abc',
        blx:'abc',
        bypmc:'abc',
        bjx:'abc',
        bgg:'abc',
        bzhb:'abc',
        bqyjc:'abc',
        bpzwh:'abc',
        bjy:'abc',
        bzdjkyw:'abc',
        byyyy:'abc',
        bzcyzsj:'abc',
        bjmdf:'abc',
        brsyy:'abc',
        bkjyw:'abc',
        bddd:'abc',
        bgytj:'abc',
        bjsqd:'abc',
        bfj:'abc',
        brsfl:'abc',
        bylfl:'abc',
        bppi:'abc'
    }]
};
var singleData = {
    id:null,
    index:null
};

$('.table-diff').html(tableDiff(data));

//滚动事件
Fn.tableDiffScroll();
//点击表格数据事件
Fn.tableDiffClick();
//鼠标表格悬停事件
Fn.tableDiffHover();
//显示比对按钮
Fn.showDiffBar(singleData);

//显示比对内容
Fn.showThan();

//绑定查看详情事件
$('#showDetail').on('click',showDetail);
//查看详情事件
function showDetail(e){
    console.log(singleData);
    if(!singleData.id){
        return;
    }
    $('.table-diff-data-content').find('[data-id='+singleData.id+']').addClass('active').siblings().removeClass('active');
    $('.table-diff-left .table-diff-data').addClass('table-diff-show-detail');
    $('.table-diff-right-all').removeClass('active');
    $('.table-diff-right-single').addClass('active');
    e.preventDefault();
}
//切换详情事件
$('.btn-toggle').on('click',hideDetail);
function hideDetail(e){
    $('.table-diff-left .table-diff-data').removeClass('table-diff-show-detail');
    $('.table-diff-data tr').removeClass('active');
    $('.table-diff-right-all').addClass('active');
    $('.table-diff-right-single').removeClass('active');
}

//弹窗修改门诊／住院单位
$('.ymzzy').on('click',ymzzyPopupFn);
function ymzzyPopupFn(){
    var companyData = {popupTitle:'门诊／住院单位'};
    $('.popup').html(popupCompanyTal(companyData)).show();
    $('.popup-close').on('click',function(){$('.popup').hide()});
}
//弹窗查看属性修改纪录
$('.btn-record').on('click',recordFn);
function recordFn(){
    var recordData = {popupTitle:'住院单位'};
    $('.popup').html(popupRecordTal(recordData)).show();
    $('.popup-close').on('click',function(){$('.popup').hide()});
}