require('../../component/login/');
require('../../component/header/');
require('../../component/footer/');
require('../../component/tabBar/');
require('../../component/searchBox/');
require('../../component/standardThan/');
require('../../component/addData/');
require('../../component/footer/');
require('./home.js');